#!/usr/bin/env python3
"""Write fixtures/manifest.json (fixture id -> paths, feature ids, hashes) and validate it.

`--verify` instead compares freshly built originals against the committed fixtures/manifest.json
(reproducibility gate used by build_all.sh).
Validation: every feature id used by a scenario/expected file exists in <fixture>/features.json and
every feature that is observable on this host has evidence in the expected files.
"""
import hashlib, json, os, sys

FX = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIXTURES = {
    "pecli": {"kind": "native_pe_x64_cli", "originals": ["original"], "expected": ["expected/scenarios.json"],
              "extra": {"wrong_remake": "wrong_remake"}, "oracle": "wine (non-certifying)"},
    "dotnetapp": {"kind": "dotnet8_console", "originals": ["original"], "expected": ["expected/scenarios.json"],
                  "extra": {}, "oracle": "dotnet 8 runtime on Linux (non-certifying)"},
    "javacli": {"kind": "java17_console_jar", "originals": ["original"], "expected": ["expected/scenarios.json"],
                "extra": {}, "oracle": "java 17 (Temurin/Microsoft OpenJDK) on the Windows host (non-certifying for other hosts)"},
    "godotgame": {"kind": "godot4_pck", "originals": ["original"], "expected": ["expected/resources.json"],
                  "extra": {}, "oracle": "GDRE tools 2.7.0 recovery (game itself not executable here)"},
    "webapp": {"kind": "pwa_and_electron_asar", "originals": ["original", "original-electron"],
               "expected": ["expected/web_scenarios.json"], "extra": {}, "oracle": "Playwright 1.56.1 + Chromium"},
}


def sha(p):
    return hashlib.sha256(open(p, "rb").read()).hexdigest()


def used_features(fx):
    used = set()
    def walk(o):
        if isinstance(o, dict):
            if isinstance(o.get("feature"), str):
                used.add(o["feature"])
            for v in o.values(): walk(v)
        elif isinstance(o, list):
            for v in o: walk(v)
    for e in FIXTURES[fx]["expected"]:
        d = json.load(open(os.path.join(FX, fx, e)))
        walk(d)
        for f in d.get("features", []) if isinstance(d, dict) else []:
            used.add(f["id"])
    return used


def build():
    doc = {"schema": 1, "note": "generated by fixtures/tools/make_fixtures_manifest.py; adapters must only read <fixture>/<originals>", "fixtures": {}}
    problems = []
    for fx, meta in FIXTURES.items():
        feats = json.load(open(os.path.join(FX, fx, "features.json")))
        ids = {f["id"] for f in feats}
        used = used_features(fx)
        for u in sorted(used - ids):
            problems.append(f"{fx}: feature {u} used in expected files but missing from features.json")
        for f in feats:
            if f["observable_on"].startswith(("linux", "host_")) and f["id"] not in used and fx != "webapp":
                problems.append(f"{fx}: feature {f['id']} claims to be observable here but has no expected evidence")
        entry = {"kind": meta["kind"], "oracle": meta["oracle"], "dir": fx, "originals": {}, "expected": {}, "features": feats,
                 "src_dir": f"{fx}/src (evaluation harness only)"}
        for o in meta["originals"]:
            mf = os.path.join(FX, fx, o + ".manifest.json")
            entry["originals"][o] = {"path": f"{fx}/{o}", "manifest": f"{fx}/{o}.manifest.json", "manifest_sha256": sha(mf),
                                     **{k: v for k, v in json.load(open(mf)).items() if k in ("file_count", "total_bytes")},
                                     "files": {e["path"]: e["sha256"] for e in json.load(open(mf))["files"]}}
        for e in meta["expected"]:
            p = os.path.join(FX, fx, e)
            entry["expected"][e] = {"path": f"{fx}/{e}", "sha256": sha(p)}
        sd = os.path.join(FX, fx, "expected", "screens")
        if os.path.isdir(sd):
            entry["expected"]["screens"] = {f: sha(os.path.join(sd, f)) for f in sorted(os.listdir(sd))}
        for k, v in meta["extra"].items():
            entry[k] = f"{fx}/{v}"
        doc["fixtures"][fx] = entry
    return doc, problems


def main():
    doc, problems = build()
    if problems:
        print("\n".join("PROBLEM " + p for p in problems)); sys.exit(1)
    path = os.path.join(FX, "manifest.json")
    if "--verify" in sys.argv:
        old = json.load(open(path))
        bad = []
        for fx, e in doc["fixtures"].items():
            for o, info in e["originals"].items():
                if info["files"] != old["fixtures"][fx]["originals"][o]["files"]:
                    bad.append(f"{fx}/{o}: built files differ from manifest.json")
        if bad:
            print("\n".join("DRIFT " + b for b in bad)); sys.exit(1)
        print("fixtures/manifest.json: originals reproduce exactly")
        return
    json.dump(doc, open(path, "w", newline="\n"), indent=2, sort_keys=True)
    open(path, "a", newline="\n").write("\n")
    print(f"wrote {path}: " + ", ".join(f"{k}({len(v['features'])} features)" for k, v in doc["fixtures"].items()))


if __name__ == "__main__":
    main()
